### PR TITLE
Added "How to use Duck with RunAbove Storage?"

### PR DESCRIPTION
**Pull request by michaelforge**
Another way to access and manage RunAbove Storage, available for Windows, Mac OS and Linux

### CODE REVIEW

**Comment by michaelforge** [comment]
Any comments would be nice!

**Comment by michaelforge** [comment]
I see that this pull request has being open for some time now.
What's need to be improved, fellas? How can I make it better?

**Comment by yadutaf** [comment]
IHMO, Runabove's knowledge base is not the best place for your tutorial. I'd rather submit it to ``Duck`` team instead. @gierschv @NicolasLM Opinion?

**Comment by michaelforge** [comment]
@yadutaf 
Hmm. It's quite RunAbove oriented.
If it's not, then I don't see why those are still here:
https://github.com/runabove/knowledge-base/blob/master/en/_posts/2014-04-22-how-to-use-cyberduck-with-openstack-swift.markdown
https://github.com/runabove/knowledge-base/blob/master/en/_posts/2015-02-07-how-to-use-S3QL-with-runabove.markdown
https://github.com/runabove/knowledge-base/blob/master/en/_posts/2015-03-12-jekyll-and-swift-object-storage.md

**Comment by yadutaf** [comment]
Start by adding this text in the tutorial then ;)

**Comment by michaelforge** [comment]
@yadutaf 
Ability to recursively is already covered here, as for AWS S3 -> Swift migration case.
This is what's make Duck more interesting - it's supporting multiple protocols at the same time: FTP, SFTP, WebDAV, Amazon S3 and OpenStack Swift. Just perfect for migration scenario. =]

**Comment by michaelforge** [comment]
My primary motivation to write this was migration between cloud storages.
Recently I discovered `rclone`, which migrating files much faster than duck.sh.

Do you need a tutorial about it here, or rA knowledgebase is not going to be expanded around OVH's services?

**Comment by yadutaf** [comment]
Thanks for your contribution. As you know, Runabove's Object Storage project graduated to OVH.com Cloud.

**Pull request closed without merging**
