### PR TITLE
Add PaaS Docker lab tutorials

### PR DESCRIPTION
**Pull request by Devatoria**

### CODE REVIEW

**Comment by yadutaf** [comment]
That's a lot of related guides. It may be worth adding a dedicated cover page, listing all possible guides to help the user find what he's looking for.

**Comment by VincentCasse** [comment]
They already have a category system to list all the related topic. For docker, that's https://community.runabove.com/kb/en/docker

In your pr, can you delete all old deprecated guides please?

**Comment by yadutaf** [comment]
+1 for deleting old SA guides. That would be confusing. This said, the category is nice to get a rough list of available guides. But you don't necessarily know where to start. Docker users are used to good documentation and ergonomy. A special post with a general introduction (what is docker, what is marothon, why do need them, what do we offer and where to get started + all the links) is necessary

**Comment by Devatoria** [comment]
I removed old SA posts and, as suggested by @yadutaf, I added an introduction guide with a little introduction of our lab and how to start.

**Pull request merged**
