### PR TITLE
new doc :  how to use sailabove webhooks

### PR DESCRIPTION
**Pull request by tgermain**
It also add some extensions to carpet's markdown renderer.

Signed-off-by: timothee.germain <timothee.germain@corp.ovh.com>

### CODE REVIEW

**Comment by yadutaf** [comment]
LGTM. @VincentCasse Can you review ? Especially, there is a ninja change in the markdown renderer

**Comment by yadutaf** [comment]
@tgermain Can you squash + sign your commits ?

**Comment by tgermain** [comment]
I removed changes of markdown renderer. Their will go into a separate PR.

**Comment by VincentCasse** [comment]
Without the ninja change, I merge it now.
Please include your change into another PR to check the others articles + fix the css

**Pull request merged**
