### PR TITLE
Use bundler to fix dependencies and run jekyll

### PR DESCRIPTION
**Pull request by guillaumebreton**
The readme tells us to use a 'gem install jekyll' which installs
the 3+ version of jekyll. The site does not run with this version of
jekyll. The usage of bundle helps to pin the version of jekyll to 2.5.3
and also pin the dependencies. It also helps to have multiple instance
of jekyll installed.

### CODE REVIEW

**Comment by yadutaf** [comment]
Interesting. @VincentCasse / @NicolasLM Opinion ? Can you confirm the version numbers ?

**Comment by NicolasLM** [comment]
Right it's better!

That leads me to think that having a container for easily building the KB would be awesome.

**Comment by guillaumebreton** [comment]
@NicolasLM I think that @thbkrkr would love that :)

**Comment by guillaumebreton** [comment]
@NicolasLM @yadutaf Just updated the version to 2.3.0.

**Comment by NicolasLM** [comment]
All right, I'm currently building the docker based on your branch.

**Comment by guillaumebreton** [comment]
@NicolasLM ok 👍

**Comment by NicolasLM** [comment]
I validated the versions. Merged, thanks!

**Pull request merged**
